# Site settings
title: "GPy Gallery"
description: > # this means to ignore newlines until "baseurl:"
  Gallery of notebook examples of gpy usage.
baseurl: "/gpy-gallery" # the subpath of your site, e.g. /blog/
url: "http://inverseprobability.com" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  lawrennd
colab: https://colab.research.google.com
nbviewer: https://nbviewer.jupyter.org

ghub:
  edit: true
  repository: gpy-gallery

author:
  name: Neil D. Lawrence

collections:
  examples:
    output: true

display:
  copy_button:
    bibtex: true
    endnote: true
    ris: true
    apa: true
  comments: true


# Build settings
markdown: kramdown
#permalink: "/:categories/:title.html"
permalink: "/:title.html"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings

analytics:
  google:
    tracking_id: UA-62968536-1
